version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into AWS ECR
      - docker login 
      - aws --version
      - $(aws ecr get-login-password --region us-east-1 no-include-email)
      - REPOSITORY_URL=536510685689.dkr.ecr.us-east-1.amazonaws.com/react-website:latest
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_VERISON | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:latest}

  build:
    commands:
      - echo Build started on 'date'
      - echo Building the react-website docker image 
      - docker build -t $REPOSITORY_URL:latest .
      - docker tag $REPOSITORY_URL:latest $REPOSITORY_URL:$IMAGE_TAG
  
  post_build:
    commands:
      - echo Build completed on 'date'
      - echo Pushing the current docker image 
      - docker push $REPOSITORY_URL:latest
      - docker push $REPOSITORY_URL:$IMAGE_TAG