apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
  labels:
    app: react-resume
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-resume
  template:
    metadata:
      labels:
        app: react-resume
    spec:
      containers:
      - name: react-resume
        image: docker.io/jaysalpatel/react-resume-kube
        ports:
        - containerPort: 80