apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-resume
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react 
  template:
    metadata:
      labels:
        app: react 
    spec:
      containers:
      - name: react-resume
        image: jaysalpatel/react-website
---
apiVersion: v1
kind: Service
metadata:
  name: react-resume
  namespace: default
spec:
  type: NodePort
  selector:
    bb: web
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30001