apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
  labels:
    app: react
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: react
    template:
      metadata:
        labels:
          app: react
      spec:
        containers:
        - name: react
          image: docker.io/jaysalpatel/react-website:latest
          ports: 
          - containerPort: 80
          - port: 3000
